allowBuilds:
  "@tailwindcss/oxide": true
  esbuild: true
  mei@https://codeload.github.com/ninjawarrior1337/mei/tar.gz/c94a1cd7a408f828e9644f9f9eeba2b2a88efc8b: set this to true or false
  "mei@https://codeload.github.com/ninjawarrior1337/mei/tar.gz/main": true
  sharp: true
  svelte-preprocess: true
